config/routes.rb
Rails.application.routes.draw do

  root to: 'site#landing', as: 'landing'

  # get 'selfies', to: 'selfies#index', as: 'selfies'
  post 'selfies', to: 'selfies#create'
  get 'selfies/new', to: 'selfies#new', as: 'new_selfie'

  # get 'api/v1/selfies/recent', to: 'selfies#recent'
  post 'api/v1/selfies/recent', to: 'selfies#recent', as: 'recent_selfie'

  get 'about', to: 'site#about', as: 'about'
  get 'feed', to: 'site#feed', as: 'feed'
  get 'profile', to: 'site#profile', as: 'profile'
  post 'profile', to: 'site#profile', as: 'profile_post'

  get 'terms', to: 'site#terms', as: 'terms'
  get 'phone', to: 'site#phone', as: 'phone'

  get 'signin', to: 'site#signin', as: 'signin'
  get 'signin-upload', to: 'site#signin_upload', as: 'signin_upload'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/models/selfie.rb
class Selfie < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
  validates :picture, presence: true
  after_initialize :default_name

  def selfie_pair
    id_version = self.in_space ? 'space_selfie_id' : 'earth_selfie_id'
    return SelfiePair.find_by "#{id_version} = ?", self.id
  end

  private

  def default_name
    self.name ||= Time.now.to_i.to_s
  end

end

app/models/selfie_pair.rb
class SelfiePair < ActiveRecord::Base
  belongs_to :user
  belongs_to :earth_selfie, :class_name => "Selfie"
  belongs_to :space_selfie, :class_name => "Selfie"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :selfies, dependent: :destroy
  has_many :selfie_pairs, dependent: :destroy

  def self.from_omniauth(auth_hash)
    where(auth_hash.slice("provider", "uid")).first || create_new_user(auth_hash)
  end

  def self.create_new_user(auth_hash)
    params = {
      provider: auth_hash['provider'],
      uid:      auth_hash['uid'],
      name:     auth_hash['info']['name'],
      # first and last name available separately from facebook
      email:    auth_hash['info']['email']
    }
    return User.create(params)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    session[:user_id] = nil if ( session[:user_id] && !User.find(session[:user_id]) )
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    reset_session
  end

  helper_method :current_user

end

app/controllers/selfies_controller.rb
class SelfiesController < ApplicationController

  include ApplicationHelper

  protect_from_forgery
  skip_before_action :verify_authenticity_token, if: :json_request?

  def index
    @selfies = Selfie.all
  end

  def new
    @selfie = Selfie.new
  end

  def create

    # post request from base station
    # http://docs.python-requests.org/en/latest/user/quickstart/#post-a-multipart-encoded-file
    if params['file']
      params['selfie'] = {:picture => params['file'], :name => params['name'], :in_space => true}
    end

    parameters = params.require(:selfie).permit(:name, :picture, :in_space)
    space_selfie = Selfie.new(parameters)

    respond_to do |format|
      format.html {
        if not space_selfie.save
          @selfie = space_selfie
          render :new
        elsif current_user
          current_user.selfies.push(space_selfie)
          redirect_to profile_path
        else
          session[:selfie_id] = space_selfie.id
          redirect_to signin_upload_path
        end
      }
      format.json {
        begin
          space_selfie.save

          image_association_ids = params['name'].split('_')
          user_id = image_association_ids[0].to_i
          earth_selfie_id = image_association_ids[1].to_i

          user = User.find(user_id)
          earth_selfie = Selfie.find(earth_selfie_id)

          selfie_pair = SelfiePair.new
          selfie_pair.earth_selfie = earth_selfie
          selfie_pair.space_selfie = space_selfie
          selfie_pair.save

          user.selfies.push(space_selfie)
          user.selfie_pairs.push(selfie_pair)

          recipient_phone = user.phone || ENV['DEFAULT_RECIPIENT_PHONE']
          send_image_text_alert(recipient_phone, space_selfie.picture.feed.url)

          render json: { :status => 200, :message => 'Successfully created selfie from satellite image' }.to_json
        rescue StandardError => e
          e.backtrace.select { |x| x.match(/humanitie/) }.each { |trace| puts trace }
          render json: { :status => 500, :message => e.inspect.gsub(/[#<>]/, '')}.to_json
        end
      }
    end
  end

  def recent
    # selfies taken on earth in the order they were uploaded
    earth_selfies = Selfie.where(:in_space => false).order(created_at: :asc)

    # return first selfie that doesn't have a pair in space
    earth_selfies.each do |earth_selfie|
      if earth_selfie.user and not earth_selfie.selfie_pair
        response = {
          'selfie' => earth_selfie,
          'status' => 200
        }
        render json: response and return
      end
    end

    # no selfie that hasn't been send to space
    response = {
        'selfie' => nil,
        'status' => 204
      }
    render json: response
  end

  protected

  def json_request?
    request.format.json?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    auth_hash = env['omniauth.auth']
    user = User.from_omniauth(auth_hash)
    session[:user_id] = user.id
    if session[:selfie_id]
      selfie = Selfie.find(session[:selfie_id])
      user.selfies.push(selfie)
      session[:selfie_id] = nil
    end
    redirect_to profile_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to landing_path #, notice: "Signed out"
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  before_filter :user_signed_in?, only: [:profile, :terms, :phone]
  before_filter :accepted_terms?, only: [:profile, :feed]
  before_filter :have_phone_number?, only: [:profile]

  def user_signed_in?
    redirect_to signin_path unless current_user
  end

  def have_phone_number?
    phone_param = params['phone']

    if phone_param and phone_param.gsub(/\D/, '').length == 10
      current_user.update_attribute(:phone, phone_param)
    elsif phone_param
      flash[:error] = 'Please enter a valid 10 digit phone number'
    end

    unless current_user.phone
      redirect_to phone_path
    end
  end

  def accepted_terms?
    terms_param = params['terms_of_service']

    if terms_param and terms_param === '1'
      current_user.update_attribute(:accepted_terms, true)
    elsif terms_param
      flash[:error] = 'Please check the box to agree to the terms and conditions'
    end

    unless current_user.accepted_terms
      redirect_to terms_path
    end
  end

  def landing
  end

  def signin
  end

  def feed
    @selfie_pairs = SelfiePair.all
  end

  def profile
    @selfies = Selfie.where(:user_id => current_user.id).order(created_at: :desc)
  end

  def terms
  end

  def phone
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def send_image_text_alert(recipient_phone, image_url)
    @twilio_client = Twilio::REST::Client.new ENV['TWILIO_SID'], ENV['TWILIO_TOKEN']

    @twilio_client.account.messages.create(
      :from => "+1#{ENV['TWILIO_PHONE']}",
      :to   => recipient_phone,
      :body => "We took your picture in space! Go to humanitiesatellite.com/profile to check it out.",
      :mediaUrl => image_url,
    )
  end

end

app/helpers/selfie_helper.rb
module SelfieHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Humanitie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/selfie/new.html.erb
<h1>Add a Picture</h1>

<%= form_for @selfie do |s| %>

  <%= s.error_messages %>
  <#= s.hidden_field :gallery_id %>
  
  <p>
    <%= s.label :name %>
    <%= s.text_field :name %>
  </p>
  
  <p>
    <%= s.file_field :picture %>
  </p>
  
  <p>
    <%= s.submit %>
  </p>

<% end %>

app/views/selfies/index.html.erb
<h1>All Selfies</h1>

<% for selfie in @selfies %>
  <div class="selfie-thumb">
    <%# image_tag selfie.picture_url.to_s %>
    <%= image_tag selfie.picture_url(:thumb).to_s %>

    <p class="name"><%= selfie.name %></p>
  </div>
<% end %>

app/views/selfies/new.html.erb
<body class="upload-selfie">

<nav>
  <%= link_to 'Back', url_for(:back) %>
</nav>

<%= form_for @selfie, :html => {:class => 'upload-form centered'} do |s| %>

  <h1>Add a Picture</h1>
  <%= s.hidden_field :name, :placeholder => 'Name your selfie' %> <br>

  <% if @selfie.errors.any? %>
    <p class='error'><%= flash[:error] %>
     <% @selfie.errors.full_messages.each do |error_message| %>
      <span><%= error_message %></span><br>
     <% end %>
    </p><br>
  <% end %>

  <button id='displayed-select'>Choose File</button> <br>
  <%= s.submit 'Submit', :id => 'submit' %>
  <%= s.file_field :picture, :id => 'hidden-select' %>

<% end %>

</body>

<script>

$('#displayed-select').click(function() {
  event.preventDefault();
  $('#hidden-select').click();
  $('#displayed-select').addClass('disabled').html('Selected');
})

$('#submit').click(function() {
  $('#submit').addClass('disabled').val('Submitted');
})

</script>

app/views/site/about.html.erb
<body class="about earth-fullpage">

  <%= link_to "Upload", new_selfie_path, class: "upload" %>

  <nav>
    <%= link_to "Profile", profile_path if current_user %>
    <%= link_to "Sign In", signin_path if !current_user %>
  </nav>

  <main>
    <h1>Humanitie</h1>

    <p>I can see clearly now the rain is gone.<br>
    I can see all obstacles in my way.<br>
    Gone are the dark clouds that had me blind.<br>
    It's gonna be a bright, bright sunshiny day.</p>

    <section class="connect">
      <a href="https://twitter.com/humanitiesat" target="_blank" class="social-media"><i class="fa fa-twitter fa-2x"></i> @humanitiesat</a>

      <a href="mailto:humanitiesatellite@gmail.com" target="_blank">humanitiesatellite@gmail.com</a>
    </section>
  </main>

</body>

app/views/site/feed.html.erb
<body class="profile">

<!-- <p class="profile-name"><#= current_user.name %></p> -->

<nav>
  <%= link_to "About", about_path %>
  <%= link_to "Sign out", signout_path %>
</nav>

<section class="feed">

<%= link_to "Upload", new_selfie_path, class: "upload" %>

<% for selfie_pair in @selfie_pairs %>
  <div class="selfie">
    <%= image_tag selfie_pair.earth_selfie.picture_url(:feed).to_s %>
    <%= image_tag selfie_pair.space_selfie.picture_url(:feed).to_s %>
  </div>
<% end %>

</section>

</body>

app/views/site/landing.html.erb
<body class="landing earth-fullpage">

  <nav>
    <%= link_to "About", about_path %>
    <%= link_to "Profile", profile_path if current_user %>
    <%= link_to "Sign In", signin_path if !current_user %>
  </nav>

  <main class="centered">
    <h1>Humanitie</h1>
    <h2>We're going to space!</h2>
    <%= link_to "Upload Picture", new_selfie_path, class: "upload" %> <br>
  </main>

</body>

app/views/site/phone.html.erb
<main class="phone centered">

<h1>One more step!</h1>
<h2>We'll send you a text when your picture's back from space. What's your number?</h2>

<% if flash[:error] %>
  <p class='error'><%= flash[:error] %></p>
<% end %>

<%= form_tag(profile_post_path, method: 'post') do %>
   <%= hidden_field_tag :phone, '' %>
   <%= phone_field_tag 'phone', '', :autofocus=>true %> <br>
   <%= submit_tag 'Let\'s go!', :name => nil, :id => 'submit' %>
<% end %>

</main>

app/views/site/profile.html.erb
<body class="profile">

<p class="profile-name"><%= current_user.name %></p>

<nav>
  <%= link_to "About", about_path %>
  <%= link_to "Sign out", signout_path %>
</nav>

<section class="feed">

<% if not @selfies.empty? %>
<%= link_to "Upload", new_selfie_path, class: "upload" %>
<%= link_to "+", new_selfie_path, class: "upload mobile" %>
<% end %>

<% for selfie in @selfies %>
  <% if selfie.picture.feed.file.exists? && selfie.user %>
    <div class="selfie">
      <%= image_tag selfie.picture_url(:feed).to_s %>
      <!-- <p class="name"><#= selfie.name %></p>
      <p class="user-name"><#= selfie.user.name %></p> -->
      <p class="date"><%= selfie.created_at.strftime('%b %d, %Y') %></p>
    </div>
  <% end %>
<% end %>

</section>

<% if @selfies.empty? %>

<section class="no-selfies">
  <h1>No photos!</h1>
  <%= link_to "Upload your first photo", new_selfie_path, class: "upload empty" %>
</section>

<% end %>

</body>

app/views/site/signin.html.erb
<main class="signin centered">

<h1>Sign In</h1>

<%= link_to "Sign in with Facebook", "auth/facebook", class: "facebook" %> <br>
<%= link_to "Sign in with Google+", "/auth/google_oauth2", class: "google" %>

</main>

app/views/site/signin_upload.html.erb
<main class="signin-upload centered">

<h1>Uploaded successfully</h1>
<h3>Now, connect your picture to your account</h3>

<%= link_to "Sign in with Facebook", "auth/facebook", class: "facebook" %> <br>
<%= link_to "Sign in with Google+", "/auth/google_oauth2", class: "google" %>

</main>

app/views/site/terms.html.erb
<body class="terms">

<h1>Terms and Conditions</h1>

<% if flash[:error] %>
  <p class='error'><%= flash[:error] %></p>
<% end %>

<section>

    <p>I bought my whole family whips; no Volvos<br>
    Next time I’m in church, please: no photos<br>
    Police escorts, everybody passports<br>
    This the life that everybody ask for</p>

    <p>This is our first beta launch!</p>

    <p>You might lose your account and any uploaded images.<br>
    Your images and name may be publicly available.</p>

    <p>If you have questions, please email humanitiesatellite@gmail.com</p>

</section>

<%= form_tag(profile_post_path, method: 'post') do %>
   <%= hidden_field_tag :terms_of_service, 0 %>
   <%= check_box_tag :terms_of_service %>
   <label>I read and agree to the terms and conditions</label>
   <%= submit_tag 'Submit', class: 'agree' %>
<% end %>

</body>